# fly.toml app configuration file generated for polished-cherry-4648 on 2023-06-16T13:29:01-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "polished-cherry-4648"
primary_region = "sjc"

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
